# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "빌드 날짜를 업데이트"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions

    PROJECT_ROOT = File.expand_path("..", Dir.pwd)
    PROJECT_DIR = File.expand_path("Build Date Example", PROJECT_ROOT)

    buildDate = Time.now.strftime("%y%m%d")

    # 빌드 날짜를 업데이트 한다
    `/usr/libexec/PlistBuddy -c "Set :BUILD_DATE #{buildDate}" "#{PROJECT_DIR}/Info.plist"`

    begin
      git_commit(path: "#{PROJECT_DIR}/Info.plist", message: "[Fastlane][ci skip] 빌드 날짜 업데이트 > #{buildDate}")
    rescue
      puts "빌드 날짜가 동일합니다."
    end
    # 빌드와 배포 작업
  end
end
